export const SEND_AUTHENTICATION = "SEND_AUTHENTICATION";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const ADD_CONVERSATION = "ADD_CONVERSATION";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const ADD_USER = "ADD_USER";
export const SET_DISAPPEARING_MESSAGE = "SET_DISAPPEARING_MESSAGE";
